config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments, only: [:new, :create, :edit, :update, :destroy] do
      member do
        put "report", to: "comments#report"
      end
    end
  end 

  resources :profiles

  resources :tags, except: :show
  get 'tags/:tag', to: 'posts#index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Belle By', root_path, class:'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Search', posts_path %></li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View Profile', profile_path(current_user.profile) %></li>
            <li><%= link_to 'Add Picture', new_post_path %></li>
            <li><%= link_to 'Edit Profile', edit_profile_path(current_user.profile) %></li>
            <li><%= link_to 'Edit Settings', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>