config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  devise_for :users, controllers: { registrations: "registrations" }

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments, only: [:new, :create, :edit, :update, :destroy] do
      member do
        put "report", to: "comments#report"
      end
    end
  end 

  resources :profiles

  resources :tags, except: :show
  get 'tags/:tag', to: 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  include Filterable

  acts_as_taggable
  acts_as_votable

  belongs_to :user
  has_many :comments
  has_one :profile, through: :user
  delegate :username, to: :profile
  
  has_many :post_treatments, dependent: :destroy
  has_many :treatments, through: :post_treatments

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  validates :picture, attachment_presence: true
  
  validates :price, presence: true
  validates :length, presence: true
  validates :comments, length: { maximum: 140 }

  validates_presence_of :treatments

  after_commit :add_tags, :check_tags 

  scope :price, -> (price) { where price: price }
  scope :hair_length, -> (hair_length) {where length: hair_length }
  scope :treatment_filter, -> (treatment) { joins(:treatments).where("treatments.id" => treatment) }
  scope :location, lambda { |location| joins(:profile).where('profiles.city = ?', location) }

  def add_tags
    if self.tag_list.to_a.exclude?(self.length)
      self.tag_list << self.length  
      self.save!
    end
  end

  def check_tags
    self.tag_list.each do |word|
      if word.match(/\s/)
        self.tag_list.delete(word)
        self.tag_list << word.split
        self.save!
      end
    end
  end

  def self.most_votes
    order(cached_votes_total: :desc)
  end

  def self.newest
    order(created_at: :desc)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :tag_cloud, only: [:index, :new]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all    
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    elsif params[:treatments].present?
      @posts = @posts.treatment_filter(params[:treatments]).distinct if params[:treatments].present?
    else
      @posts = Post.filter(params.slice(:price, :location))
      @posts = @posts.hair_length("#{params["hair_length"]}") if params[:hair_length].present?
    end

    @posts = @posts.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    set_stylist
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post.upvote_by current_user
    render action: 'show', :id => @post.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:stylist, :treatment, :price, :length, :comment, :picture, :user_id, :tag_list, :tag, { tag_ids: [] }, :tag_ids, treatment_ids: [])
    end

    def tag_cloud
      @tags = Post.tag_counts_on(:tags).order('count desc').limit(20)
    end

    def set_stylist
      @post.stylist = current_user.id if current_user.category == "Stylist"
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper

  def likes(post)
    if post.get_likes.size == 1
      "#{post.get_likes.size} like"
    else post.get_likes.size > 1
      "#{post.get_likes.size} likes"
    end
  end

  def stylist(post)
    if post.stylist.present?
      return(link_to "By #{User.find_by(id: post.stylist).username}", profile_path(post.stylist))
    else
      return("#{post.user.username}")
    end
  end

  def searchbox_checked_checkbox(treatment, params)
    if params.present? 
      true if params.include?(treatment.id.to_s)
    else
      false
    end
  end

  def form_checked_checkbox(post, treatment)
    true if post.treatments.include?(treatment) 
  end

end

app/views/posts/_comments.html.erb
<% @post.comments.live.each do |comment| %>
  <p style="margin:5px">
    <strong>
      <%= link_to "#{comment.user.profile.username}", profile_path(comment.user.profile), style:'color:#52489C' %>
    </strong>
    <%= comment.body %>
    <% if owner(comment) %>
      <%= link_to 'Edit', edit_post_comment_path(@post, comment), style:'font-size:.7em' %>
    <% end %>
    <%= link_to 'report', report_post_comment_path(@post, comment), method: :put, type:'submit', style:'font-size:.7em' %>
  </p>
<% end %>
<p style="text-align: right"><%= link_to 'Add Comment', new_post_comment_path(@post) %><p>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <div style="text-align:center">
    <img height="100%" width="60%" alt="Image preview...">
  </div>

  <div class="form-group">
    <%= f.input :picture, as: :file, :input_html => {:onchange => "previewFile()"} %>

    <% if current_user.category == "Customer" %>
      <%= f.input :stylist, collection: User.where(category: "Stylist"), prompt: "Find Stylist", input_html: { class: 'form-control' }, label: "Stylist", label_method: :username %>
    <% end %>

    <div>
      <% Treatment.all.each do |treatment| %>
        <%= check_box_tag "post[treatment_ids][]", treatment.id, form_checked_checkbox(@post, treatment) %>
        <%= treatment.name %>
      <% end %>
    </div>
    <br>
    <%= f.input :length, collection: ['Shaved', 'Short', 'Medium', 'Long'], prompt: "Select length", input_html: { class: 'form-control' } %>
    <%= f.input :price, collection: Price.all, label_method: :amount, prompt: "Select price", input_html: { class: 'form-control' } %>
    <em style="float:right">(Seperate Tags by comma)</em>
    <%= f.input :tag_list, as: :text, input_html: { class: 'form-control' }, placeholder: "#{popular_tags}" %>
    <%= f.input :comment, as: :text %>  
    <hr>
    <%= f.button :submit, 'Upload Picture', class:'btn btn-pink btn-block' %>

  </div>

<!-- Need to work out way of adding gender -->
<% f.input :gender, collection: ['Haircut', 'Nails', 'Eyelashes'], input_html: { class: 'form-control' } %>

<% end %>

app/views/posts/_gallery.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-3 col-md-offset-0 col-lg-3 col-lg-offset-0 gallery-image">
  <%= link_to post do %>
    <div class="panel panel-default" id="post-panel">
      <div class="panel-body">
        <%= image_tag post.picture, id:'post-index-image' %>
      </div>
      <div class="panel-footer" style="background: white;border: 0px;padding-top: 5px;padding-bottom: 0px">
      <div class="row">
        <div class="col-xs-6">
          <p><%= stylist(post) %></p>
        </div>
        <div class="col-xs-6"  style="text-align: right;padding:5px;padding-right:15px;">
          <span style="color:#777;"><%= post.get_likes.size %>&nbsp;</span>
          <%= link_to like_post_path(post), method: :put, "type" => "submit", "data-toggle" => "popover", "data-trigger" => "hover", "data-content" => "Love it!", "data-placement" => "top" do %>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>

      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

app/views/posts/_table.html.erb
  <div class="panel panel-default">
  
    <div class="panel-heading">
      <h3>Posts</h3>
    </div>

    <div class="panel-body">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>#</th>
            <th>Treatment</th>
            <th>Comment</th>
            <th>Stylist</th>
            <!-- <th>Gender</th> -->
            <th>Price</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.id %></td>
              <td><%= post.treatment %></td>
              <td><%= post.comment %></td>
              <td><%= post.user.profile.first_name %></td>
              <!-- <td><% post.gender %></td> -->
              <td><%= post.price %></td>
              <td><%= link_to 'Show', post %></td>
              <td><%= link_to 'Edit', edit_post_path(post) %></td>
              <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Edit Post</h4>
      </div>
      <div class="panel-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
    <%= link_to 'Show', @post, class:'btn btn-default' %>
    <%= link_to 'Back', :back, class:'btn btn-default' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-md-10 col-md-offset-1">
    <div class="panel panel-default search-bar">
      <div class="panel-body">
        <%= form_tag posts_path, :method => :get, :class => "form-inline" do %>
          <div class="form-group">
            <% Treatment.all.each do |treatment| %>
              <%= check_box_tag("treatments[]", treatment.id, searchbox_checked_checkbox(treatment, params[:treatments]) ) %>
              <%= treatment.name %>
            <% end %>
            <%= select_tag :hair_length, options_for_select(["Shaved", "Short", "Medium", "Long"], selected: params[:hair_length]), html_options = { class:'form-control', prompt: "Length" } %>
            <%= select_tag :price, options_from_collection_for_select(Price.all, 'id', 'characters', selected: params[:price]), html_options = { class:'form-control', prompt: "Price" } %>
            <%= select_tag :location, options_for_select(Profile.all.to_a.pluck(:city).compact.uniq, selected: params[:location]), html_options = { class:'form-control', prompt: "Location" } %>
          </div>
          <%= submit_tag 'Search', class:'btn btn-default btn-pink' %>
          <i class="fa fa-arrow-down pull-right hidden-sm hidden-xs" style="padding:20px" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample"></i>
        <% end %>
      </div>
      <div class="panel-footer collapse hidden-sm hidden-xs" id="collapseExample">
          <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class, style: 'color: #59C3C3;' %>
          <% end %>
          <br>
        <%= link_to 'reset', posts_path %>
      </div>
    </div>

  </div>
</div>

<div class="row">
  <%= render partial: 'posts/gallery', collection: @posts.most_votes, as: :post %>
</div>


<%= will_paginate @posts, class:'digg_pagination pull-right' %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>New Post</h4>
      </div>
      <div class="panel-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
    <%= link_to 'Back', :back, class:'btn btn-default' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
    <div class="panel panel-default" id="post-panel">
      <div class="panel-body">
        <%= image_tag @post.picture, id:'post-panel-image' %>
      </div>
      <div class="panel-footer" style="padding-top: 15px">
        <h4 style="color:#337ab7"><%= stylist(@post) %></h4>
        <h5><%= Price.find_by(id: @post.price).characters %></h5>
        <p><%= @post.comment %></p>
        
        <i class="fa fa-tags" aria-hidden="true" style="color:#52489C"></i>
        <% @post.tag_list.each do |tag| %>
          <%= link_to tag, tag_path(tag), class:'tag' %>
        <% end %>
        
          <%= link_to like_post_path(@post), method: :put, "type" => "submit", "class" => "pull-right", "data-toggle" => "popover", "data-trigger" => "hover", "data-content" => "Love it!" do %>
            <i class="fa fa-heart fa-2x" aria-hidden="true"></i>
          <% end %>
          <p class="pull-right"><%= @post.get_likes.size %>&nbsp;&nbsp;</p>
        <hr>
        <%= render partial: 'comments', locals: {post: @post} %>

      </div>
    </div>
    <% if owner(@post) %> <%= link_to 'Edit', edit_post_path(@post), class:'btn btn-default' %><% end %>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>